java_test(
    name = "RateLimitedRequestHandlerTest",
    srcs = ["RateLimitedRequestHandlerTest.java"],
    deps = [
        "//src/java/com/caston/challenge/server:RateLimitedRequestHandler",
        "//src/java/com/caston/challenge/server:RateLimiter",
        "//src/java/com/caston/challenge/server:RequestHandler",
        "@mockito//jar",
    ],
)
