java_test(
    name = "ServerTest",
    srcs = ["ServerTest.java"],
    deps = [
        "//src/java/com/caston/challenge/server:RateLimiter",
        "//src/java/com/caston/challenge/server:RequestHandler",
        "//src/java/com/caston/challenge/server:Server",
        "@mockito//jar",
    ],
)
