java_library(
  name = "DemoHttpHandler",
  srcs = ["DemoHttpHandler.java"],
)

# Main entry point for demo.
java_binary(
    name = "DemoMain",
    srcs = ["DemoMain.java"],
    deps = [
      "DemoHttpHandler",
    ],
)
